name: flash_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  cloud_firestore: ^4.15.6
  fluttertoast: ^8.2.4
  animated_text_kit: ^4.2.2
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - images/logo.png

  uses-material-design: true

